name: hello from the windows github action 
on:
    workflow_dispatch:
jobs:
    say-hello:
        runs-on: windows-latest
        steps:
          - run: echo "hello from the github workflows from windows os!"
    say-bye:
        runs-on: ubuntu-latest
        steps:
            - run: echo "hello from 2nd job on ubuntu os!"

