name: multi-job with need github action 
on:
    workflow_dispatch:
  #push:
   # branches:
    #  - main
jobs:
  tf-init:
    runs-on: ubuntu-latest
    steps:
        - run: echo "tf init in progress!" 
  tf-validate:
    runs-on: ubuntu-24.04
    needs:
        - tf-init
    steps:
        - run: echo "tf validate in progress!"
  tf-plan:
    runs-on: ubuntu-24.04
    needs:
      - tf-init
      - tf-validate
    steps:
        - run: echo "tf plan in progress!"